version: '2'

services:

  bash:
    build:
      context: .
    image: bethanysprag/triangulargreenness:latest
    entrypoint: /bin/bash
    working_dir: /work
    volumes:
      - '.:/work:rw'

  test:
    build:
      context: .
    image: bethanysprag/triangulargreenness:latest
    command: bash -c 'nosetests -v -s --with-coverage --cover-inclusive --cover-package TriangularGreenness --debug=TriangularGreenness'
    working_dir: /work
    volumes:
      - '.:/work:rw'
